Construct server
papakapa/Music-Streaming pull request #3
Opened 2020-11-12 14:32 UTC by papakapa

2020-11-12 15:08 UTC, m4eryk requested changes

2020-11-12 15:08 UTC, m4eryk commented on serv.js
> +mongoose.connect("mongodb+srv://kiryl:1111@cluster0.2ltpu.mongodb.net/music?retryWrites=true&w=majority", {
move url to const

2020-11-12 15:08 UTC, m4eryk commented on serv.js
> +    console.log(req.body);
remove all console.log

2020-11-12 15:08 UTC, m4eryk commented on serv.js
> +                console.log('Track exist or other error', err);
use console.error

2020-11-15 15:15 UTC, papakapa commented on config/default.json
> +  "PORT": 63341,
add SCREAMING SNAKE CASE

2020-11-15 15:15 UTC, papakapa commented on config/default.json
> +
add new line in the of file

2020-11-17 15:42 UTC, merged