Feature/auth
papakapa/Music-Streaming pull request #7
Opened 2020-11-26 17:37 UTC by papakapa

complete server auth/registr
complete front auth/registr

2020-11-28 11:03 UTC, m4eryk requested changes

2020-11-28 11:03 UTC, m4eryk commented on front/music-app/src/reducers/userReducer.js
> +const SET_USER = 'SET_USER';
в отдельный файл

2020-11-29 15:57 UTC, papakapa commented on front/music-app/src/components/Regs.jsx
> +            const res = await axios.post('http://localhost:63341/registration',{
вынес в файл с роутами

2020-11-29 15:57 UTC, papakapa commented on front/music-app/src/App.js
> +                            <Switch>
создал для приватного доступа и логина с регистрацией

2020-11-29 15:57 UTC, papakapa commented on back/serv.js
> +        console.log(req.body);
удалил

2020-11-29 15:57 UTC, papakapa commented on front/music-app/.eslintrc
> +  "rules": {
добавил правила для пробелов

2020-11-29 15:58 UTC, papakapa commented on front/music-app/src/reducers/userReducer.js
> +const SET_USER = 'SET_USER';
перенес в отдельный файл с константами под названием actions.js

2020-11-29 16:17 UTC, papakapa commented
еще пофиксил добавление песни на монго
там была ошибка с тем что сначала приходило только имя и автор
а только потом с постером и треком
теперь приходит все сразу

2020-11-29 18:57 UTC, m4eryk commented on front/music-app/src/App.js
> +    console.log(store);
)))))))

2020-11-29 18:57 UTC, merged